networks:
  proxy:
    external: true

services:
  homepage:
    build: .
    hostname: homepage
    container_name: homepage
    environment:
      - OPENWEATHER_API_KEY
      - PEXELS_API_KEY
      - UB_ADMIN_EMAIL
      - UB_ADMIN_PASSWORD
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - ./pocketbase/pb_data:/pb/pb_data
